name: stockmarketbackend
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' # Only deploy master
    steps:
      - uses: actions/checkout@v2
      # - name: Run production migration
      # Note: disabled migrate deploy in favour of using the Procfile release phase
      #   run: npm run migrate:deploy
      #   env:
      #     DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - uses: akhileshns/heroku-deploy@v3.12.12
        name: Deploy to Heroku
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
